/* tslint:disable */
/* eslint-disable */
/**
 * attachmentAV
 * An SDK to integrate virus and malware scan capabilities into JavaScript / TypeScript applications. Scan files for viruses, trojans, and other kinds of malware with attachmentAV powered by Sophos.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageResultQuota
 */
export interface UsageResultQuota {
    /**
     * 
     * @type {number}
     * @memberof UsageResultQuota
     */
    limit?: number;
    /**
     * 
     * @type {string}
     * @memberof UsageResultQuota
     */
    period?: string;
}

/**
 * Check if a given object implements the UsageResultQuota interface.
 */
export function instanceOfUsageResultQuota(value: object): value is UsageResultQuota {
    return true;
}

export function UsageResultQuotaFromJSON(json: any): UsageResultQuota {
    return UsageResultQuotaFromJSONTyped(json, false);
}

export function UsageResultQuotaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageResultQuota {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'period': json['period'] == null ? undefined : json['period'],
    };
}

export function UsageResultQuotaToJSON(json: any): UsageResultQuota {
    return UsageResultQuotaToJSONTyped(json, false);
}

export function UsageResultQuotaToJSONTyped(value?: UsageResultQuota | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'period': value['period'],
    };
}

