/* tslint:disable */
/* eslint-disable */
/**
 * attachmentAV
 * An SDK to integrate virus and malware scan capabilities into JavaScript / TypeScript applications. Scan files for viruses, trojans, and other kinds of malware with attachmentAV powered by Sophos.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsageResultQuota } from './UsageResultQuota';
import {
    UsageResultQuotaFromJSON,
    UsageResultQuotaFromJSONTyped,
    UsageResultQuotaToJSON,
    UsageResultQuotaToJSONTyped,
} from './UsageResultQuota';

/**
 * 
 * @export
 * @interface UsageResult
 */
export interface UsageResult {
    /**
     * 
     * @type {number}
     * @memberof UsageResult
     */
    credits?: number;
    /**
     * 
     * @type {UsageResultQuota}
     * @memberof UsageResult
     */
    quota?: UsageResultQuota;
}

/**
 * Check if a given object implements the UsageResult interface.
 */
export function instanceOfUsageResult(value: object): value is UsageResult {
    return true;
}

export function UsageResultFromJSON(json: any): UsageResult {
    return UsageResultFromJSONTyped(json, false);
}

export function UsageResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageResult {
    if (json == null) {
        return json;
    }
    return {
        
        'credits': json['credits'] == null ? undefined : json['credits'],
        'quota': json['quota'] == null ? undefined : UsageResultQuotaFromJSON(json['quota']),
    };
}

export function UsageResultToJSON(json: any): UsageResult {
    return UsageResultToJSONTyped(json, false);
}

export function UsageResultToJSONTyped(value?: UsageResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credits': value['credits'],
        'quota': UsageResultQuotaToJSON(value['quota']),
    };
}

